

ubuntu:
	sudo apt-get install -y build-essential gfortran openmpi-bin libopenmpi-dev python python-dev python-pip git python-tk
	pip3 install requests matplotlib numpy scipy mpi4py --user

install: 
	bash install.sh


	
