#!/bin/bash
#
target=${2:-install}

if [[ $1 == 'mac.mk' || $1 == 'ubuntu.mk' || $1 == 'centos.mk' || $1 == 'arch.mk' || $1 == 'fedora.mk' || $1 == 'suse.mk' || $1 == 'debian.mk' ]]; then
    make -f "$1" "$target"

else
    echo "$1 not supported! Currently supported install commands:"
    echo "- bash install mac.mk"
    echo "- bash install ubuntu.mk"
    echo "- bash install centos.mk"
    echo "- bash install arch.mk"
    echo "- bash install fedora.mk"
fi
