
# https://framagit.org/fiat-tux/hat-softwares/lutim/wikis/dependencies

dependencies:
	sudo apt-get install -y carton
	sudo apt-get install -y build-essential libssl-dev shared-mime-info libpq-dev zlib1g-dev
	sudo apt-get install -y perlmagick



