# https://github.com/ashishb/dotfiles/blob/master/.travis.yml

branches:
  except:
    - dev

# https://stackoverflow.com/questions/27644586/how-to-set-up-travis-ci-with-multiple-languages
# Test on Both ubuntu
matrix:
  include:
    - name: ubuntu 18.04
      os: linux
      dist: bionic
      sudo: false
      script:
        - bash install ubuntu.mk
