#!/bin/bash
SUPPORTED_DISTS=("mac" "ubuntu" "centos" "arch" "fedora" "suse" "debian")

function usage {
    echo "Usage: $0 {${SUPPORTED_DISTS[@]}} [target]"
    exit 1
}

if [[ $# -lt 1 ]]; then
    usage
fi

dist=$1
target=$2

if [[ ! " ${SUPPORTED_DISTS[@]} " =~ " ${dist} " ]]; then
    echo "$dist not supported!"
    usage
fi

if [[ ! -f "${dist}.mk" ]]; then
    echo "Error: ${dist}.mk does not exist."
    exit 1
fi

echo "Hi! I'm going to install tooling and tweak your system settings. Here I go..."

if make -f "${dist}.mk" install && make install "${target}"; then
    echo "Installation completed successfully!"
else
    echo "Error: Installation failed!"
    exit 1
fi
