dwm:
	git clone git@github.com:joamatab/dwm.git

dwmblocks:
	git clone git@github.com:joamatab/dwmblocks.git

ubuntu:
	sudo apt install libxinerama1 libxinerama-dev
	sudo apt install libxbc-res0-dev
	sudo apt install libxcb-xinerama0 libxcb-xinerama0-dev

debian:
	sudo apt install libx11-xcb-dev
